// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVNDQCjdH3MezJ5lKie6vduNwMMgDn3kc',
    appId: '1:684322104478:web:2e2260a1a8f7853641c78f',
    messagingSenderId: '684322104478',
    projectId: 'impratical-posting',
    authDomain: 'impratical-posting.firebaseapp.com',
    storageBucket: 'impratical-posting.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdAOrBTIv-D2rO6VrJ7LegI-jnB2MduEM',
    appId: '1:684322104478:android:18ecfbd10f2937b241c78f',
    messagingSenderId: '684322104478',
    projectId: 'impratical-posting',
    storageBucket: 'impratical-posting.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASIs2dm_v1oXWnDGsLv5vXpl0G_b7PlZ4',
    appId: '1:684322104478:ios:9554670a3b8d036b41c78f',
    messagingSenderId: '684322104478',
    projectId: 'impratical-posting',
    storageBucket: 'impratical-posting.firebasestorage.app',
    iosBundleId: 'com.example.impraticalPosting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASIs2dm_v1oXWnDGsLv5vXpl0G_b7PlZ4',
    appId: '1:684322104478:ios:9554670a3b8d036b41c78f',
    messagingSenderId: '684322104478',
    projectId: 'impratical-posting',
    storageBucket: 'impratical-posting.firebasestorage.app',
    iosBundleId: 'com.example.impraticalPosting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVNDQCjdH3MezJ5lKie6vduNwMMgDn3kc',
    appId: '1:684322104478:web:7510e426e0390af641c78f',
    messagingSenderId: '684322104478',
    projectId: 'impratical-posting',
    authDomain: 'impratical-posting.firebaseapp.com',
    storageBucket: 'impratical-posting.firebasestorage.app',
  );
}
